apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-test
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 10.0.0.229
    path: "/exports"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-test
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nfs-jump
spec:
  replicas: 1
  selector:
    name: nfs-jump
  template:
    metadata:
      labels:
        name: nfs-jump
    spec:
      containers:
      - image: ubuntu
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 60; done;" ]
        imagePullPolicy: IfNotPresent
        name: jump
        volumeMounts:
          # name must match the volume name below
          - name: nfs-test
            mountPath: "/mnt"
      volumes:
      - name: nfs-test
        persistentVolumeClaim:
          claimName: nfs-test