
kind: ServiceAccount
apiVersion: v1
metadata:
  name: hashicorp-vault

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hashicorp-vault
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hashicorp-vault
roleRef:
  kind: Role
  name: hashicorp-vault
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: hashicorp-vault

---
# This binding allows the deployed Vault instance to authenticate clients
# through Kubernetes ServiceAccounts (if configured so).
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hashicorp-vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: hashicorp-vault
    namespace: default